"""Hive parser for raw hive files."""

# class Extractor:
#     def fetch(self, source) -> RawPage: ...

# class Normalizer:
#     def transform(self, raw: RawPage) -> NormalizedDoc: ...

# class Segmenter:
#     def split(self, doc: NormalizedDoc, *, policy) -> list[Chunk]: ...

# class Enricher:
#     def apply(self, chunks: list[Chunk]) -> list[Chunk]: ...

# class Embedder:
#     def encode(self, chunks: list[Chunk], model: str) -> list[Embedding]: ...

# class Indexer:
#     def upsert(self, embeddings: list[Embedding], **opts) -> IndexRef: ...
