---
name: Publish to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - docs/**
      - mkdocs.yml

permissions:
  contents: write

jobs:
  publish-pages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joejcollins/sandra-benes:latest
      options: --user root # needs to be root or the checkout fails.

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          clean: true
          fetch-depth: 0

      - name: Build and deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make venv
          make publish
...
