---
name: Run the Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/run-all-tests.yml
      - src/**
      - tests/**

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joejcollins/sandra-benes:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          clean: true

      - name: Run Python tests.
        run: |
          make venv
          make report
          make lint
          make test
...
